# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCNnkg61Ph7Xix8wyBwJFTR4YIVCb-IE
"""

#!/usr/bin/env python
from distutils.core import setup
setup(
 name='{name-of-your-project}',
 version='1.0',
 author='{your-full-name-or-your-github-username}',
 license='MIT',
 long_description=open('README.md').read(),
)